# git tag 0.0.1
# git push --tags
---
image: docker:stable

services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  only:
    - tags
  script:
    - export IMAGE_NAME="$CI_REGISTRY_IMAGE"
    - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG
